xml_path: "g1_description/g1_liao.xml"
# xml_path: "g1_description/scene.xml"
# xml_path: "g1_description/g1_29dof_LieDown.xml"
simulation_dt: 0.002
control_decimation: 10
ghost_enabled: true   # show reference motion ghost; toggle with G key at runtime
tau_limit: [88, 139, 88, 139, 50, 50,
            88, 139, 88, 139, 50, 50,
            88, 50, 50,
            25, 25, 25, 25, 25, 5, 5,
            25, 25, 25, 25, 25, 5, 5
           ]