net: enp2s0
num_joints: 29

lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"

control_dt: 0.02

error_over_time: 5

logging:
  enabled: true      # set true to record a score log
  log_dir: "logs"
  tag:     "score"
  states:  ["SKILL_SCORE", "LOCOMODE"]  # FSM states to record