module mjlab {
  module msg {
    module dds_ {
      struct BridgeState_ {
        unsigned long long timestamp_us;
        unsigned long long tick;
        sequence<float, 29> q;
        sequence<float, 29> dq;
        sequence<float, 4> imu_quat_wxyz;
        sequence<float, 3> imu_gyro;
        sequence<octet, 24> remote_raw;
      };

      struct BridgeCmd_ {
        unsigned long long timestamp_us;
        unsigned long long seq;
        sequence<float, 29> q_des;
        sequence<float, 29> kp;
        sequence<float, 29> kd;
        octet request_damping;
        octet exit_requested;
      };
    };
  };
};
